import { GoogleGenAI, Modality, GenerateContentResponse } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
    throw new Error("API_KEY environment variable is not set.");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

export async function generateHeadshot(
  base64Image: string,
  mimeType: string,
  stylePrompt: string
): Promise<string> {
    try {
        const response: GenerateContentResponse = await ai.models.generateContent({
            model: 'gemini-2.5-flash-image',
            contents: {
              parts: [
                {
                  inlineData: {
                    data: base64Image,
                    mimeType: mimeType,
                  },
                },
                {
                  text: stylePrompt,
                },
              ],
            },
            config: {
                responseModalities: [Modality.IMAGE],
            },
        });
      
        for (const part of response.candidates?.[0]?.content?.parts || []) {
            if (part.inlineData) {
              return part.inlineData.data;
            }
        }
        
        throw new Error("No image was generated by the API.");
        
    } catch (error) {
        console.error("Error calling Gemini API:", error);
        if (error instanceof Error) {
            throw new Error(`Failed to generate headshot: ${error.message}`);
        }
        throw new Error("An unknown error occurred during image generation.");
    }
}
